site_name: Cluster IALab
nav:
  - Home: index.md
  - Inducción al Clúster: intro.md
  - Almacenamiento: storage.md
  - Uso de SLURM: slurm.md
  - Solicitud de Recursos Adicionales: additional_resources.md
  - Ejemplos de SLURM: slurm_examples.md
  - Uso de SSH: ssh.md
  - Política de Uso: usage_policy.md
  - FAQ: faq.md
  - Monitoreo de Recursos 🔗: https://sysadminscenia.grafana.net/public-dashboards/8208a7202e7d4bd3ad6ed793a5286a7a

theme: readthedocs

plugins:
  - open-in-new-tab

markdown_extensions:
  - attr_list
