site_name: Cluster IALab
nav:
  - Introducción: index.md
  - Primeros Pasos:
    - Primeros Pasos / Registro: onboarding.md
    - Hardware del Clúster: hardware.md
    - Almacenamiento: storage.md
    - Política de Uso: usage_policy.md
  - Instrucciones y Guías:
    - SLURM: slurm.md
    - Ejemplos de SLURM: slurm_examples.md
    - SSH: ssh.md
  - Solicitudes:
    - Solicitud de Recursos Adicionales: additional_resources.md
  - Otros:
    - FAQ: faq.md
    - Monitoreo de Recursos 🔗: https://sysadminscenia.grafana.net/public-dashboards/8208a7202e7d4bd3ad6ed793a5286a7a
    - Compute Grants: compute_grants.md

theme: readthedocs

plugins:
  - open-in-new-tab

markdown_extensions:
  - attr_list
